package org.example.bot.settings.enums.artists;

public enum HermitageArtists {

    AVRESE ("Аврезе"),
    ALIKS ("Аликс Ив"),
    AMELIN ("Амелин"),
    ARTSER ("Артсер"),
    BAZILE ("Базилье"),
    BEKKER ("Беккер"),
    BARBE ("Барбье"),
    BARTEL ("Бартель"),
    BARTSON ("Бартсон"),
    BELLANJ ("Белланж"),
    BONNAR ("Боннар"),
    BORRA ("Борра"),
    BOSH ("Босх"),
    BOTICHELLI ("Ботичелли"),
    BRAUVER ("Браувер"),
    BREGEL_P ("Брейгель Питер"),
    BREGEL_Y ("Брейгель Ян"),
    BREIN ("Брейн"),
    BUALI ("Буальи"),
    BUFFE ("Бюффе"),
    VAN_GOG ("Ван Гог"),
    VAN_DEIK ("Ван Дейк"),
    VATTO ("Ватто"),
    VELASKES ("Веласкес де Сильва"),
    VERONESE ("Вероньезе"),
    VEROKKO ("Верроккьо"),
    VIDAL ("Видаль"),
    VILEGAS ("Вильегас-и-Кордеро"),
    VLAMINK ("Вламиник"),
    VOS_PAUVEL ("Вос Паувель"),
    VOTE ("Вотье"),
    GALLE ("Галле"),
    GVIDI ("Гвиди"),
    GOGEN ("Гоген"),
    GOROFALO ("Горофало"),
    GRUTCNER ("Грютцнер"),
    GREZ ("Грёз"),
    DEGA ("Дега"),
    DESUBLEO ("Дезублео"),
    DENI ("Дени"),
    DENNER ("Деннер"),
    DEREN ("Дерен"),
    DJAMPERTION ("Джампьетрино"),
    DJORDJONE ("Джорджоне"),
    DOME ("Домье"),
    DUFI ("Дюфи"),
    JEROM ("Жером"),
    IOS ("Иос ван Клеве"),
    IORDANS ("Йорданс"),
    KAMPEDONK ("Кампедонк"),
    KAMPILI ("Кампильи"),
    KAPRIOLA ("Каприола"),
    KARAVAJO ("Караваджо"),
    KARER ("Карьер"),
    KENT ("Кент Рокуэлл"),
    KNAUS ("Кнаус"),
    KOTTE ("Котте"),
    KRANAH ("Кранах"),
    KRESPI ("Креспи"),
    LAMBERT ("Ламберт"),
    LEJE ("Леже"),
    LEIBL ("Лейбль"),
    LEONARDO ("Леонардо да Винчи"),
    LUKA ("Лука Джордано"),
    MANDEIN ("Мандейн"),
    MARKE ("Марке"),
    MATISS ("Матисс"),
    MATTEO ("Маттео"),
    MELCI ("Мельци"),
    MILLE ("Милле"),
    MONE ("Моне Клод"),
    MORELSE ("Морельсе"),
    MOURER ("Моурер"),
    MURILO ("Мурильо"),
    NAGEL ("Нагель"),
    NEMO ("Неизвестный художник"),
    NEISHATEL ("Нейшатель"),
    NIKKOLO ("Никколо ди Сер Соццо"),
    PALMA ("Пальма Якопо"),
    PARKER ("Паркер"),
    PEREDA ("Переда"),
    PERRONO ("Перроно"),
    PETTENKOFEN ("Петтенкофен"),
    PIZIS ("Пизис"),
    PIKACCO ("Пикассо"),
    PISSARO ("Писсаро"),
    PLEPP ("Плепп"),
    POTTER ("Поттер"),
    PIETRO ("Пьетро"),
    RAFAEL ("Рафаэль"),
    REINA ("Рейна"),
    REMBRANT ("Рембрант"),
    RENUAR ("Ренуар"),
    REFREJE ("Рефрежье"),
    RISSANEN ("Риссанен"),
    RISHAR ("Ришар"),
    ROIMERSVALE ("Роймерсвале"),
    RUBENS ("Рубенс"),
    RUSSO ("Руссо"),
    SANCHES ("Санчес Коэльо"),
    SEZANN ("Сезанн"),
    SISLEI ("Сислей"),
    SNEIDERS ("Снейдерс"),
    STANCIONE ("Станционе"),
    STEVENS ("Стевенс"),
    STREIS ("Стрейс"),
    SUTIN ("Сутин"),
    TENIRS ("Тенирс"),
    TICIAN ("Тициан"),
    TOMA ("Тома"),
    TRUIBER ("Трйебер"),
    TUSKETS ("Тускетс-и-Маньон"),
    FAVORI ("Фавори"),
    FANTEN ("Фантен-Латур"),
    FOKSEIL ("Фоксёйль"),
    FRAGONAR ("Фрагонар"),
    FRANC ("Франс Поурбус"),
    FRANCHESKINI ("Франческини"),
    FRIDRIH ("Фридрих Каспар"),
    FRIEZ ("Фриез"),
    HAITMULLER ("Хайтмюллер"),
    HEISUM ("Хейсум"),
    HEM ("Хем"),
    HOVE ("Хове"),
    SHEFFRUA ("Шеффруа"),
    SHTUK ("Штук"),
    EDELFEL ("Эдельфель"),
    EITEVAL ("Эйтеваль"),
    EL ("Эль Греко"),
    EMSEN ("Эмзен"),
    ESPINS ("Эспина-и-Капо"),
    YAKOBS ("Якобс Дирк"),
    YANSEN ("Янсен");


    private final String artName;

    HermitageArtists(String artName) {
        this.artName = artName;
    }

    public String getArtName() {
        return artName;
    }

}
