package org.example.bot.settings.enums.artists;

public enum RusMusArtists {

    R_ABUTKOV ("Абутков"),
    R_AIVAZOVSKY ("Айвазовский"),
    R_ALTMAN ("Альтман"),
    R_ANNENKOV ("Анненков"),
    R_ARCHIPOV ("Архипов"),
    R_ARNAUTOV ("Арнаутов"),
    R_BAKST ("Бакст"),
    R_BASHKIRCEVA("Башкирцева"),
    R_BELKIN ("Белкин"),
    R_BENUA ("Бенуа"),
    R_BILIBIN ("Билибин"),
    R_BOGDANOV ("Богданов-Бельский"),
    R_BOGOLUBOV ("Боголюбов"),
    R_BODAREVSKY ("Бодаревский"),
    R_BORISOV_MUSATOV ("Борисов-Мусатов"),
    R_BRODSKY ("Бродский"),
    R_BRONNIKOV ("Бронников"),
    R_BRULLOV ("Брюллов"),
    R_BRUNI ("Бруни"),
    R_VASNECOV_V ("Васнецов В."),
    R_VENECIANOV ("Венецианов"),
    R_VENIG ("Вениг"),
    R_VERECHAGIN ("Верещагин"),
    R_VRUBEL ("Врубель"),
    R_GE ("Ге"),
    R_GINE ("Гине"),
    R_GONCHAROVA ("Гончарова"),
    R_GRABAR ("Грабарь"),
    R_GRIGOREV ("Григорьев"),
    R_GUN ("Гун"),
    R_DELAVOSKADOVSKAYA ("Делла-Вос-Кардовская"),
    R_DEMIDOV ("Демидов"),
    R_DMITRIEV ("Дмитриев-Оренбургский"),
    R_DOBUJINSKY ("Добужинский"),
    R_DREVIN ("Древин"),
    R_DUBOVSKY ("Дубовский"),
    R_JILINKY ("Жилинский"),
    R_JUKOVSKY ("Жуковский"),
    R_JURAVLEV ("Журавлев"),
    R_IVANOV_AA ("Иванов А.А."),
    R_IVANOV_AM ("Иванов А.М."),
    R_IVANOV_SP ("Иванов С.П."),
    R_KALMAKOV ("Калмаков"),
    R_KANDINSKY ("Кандинский"),
    R_KASATKIN ("Касаткин"),
    R_KIVSHENKO ("Кившенко"),
    R_KLEVER ("Клевер"),
    R_KLODT ("Клодт фон Юргенсбург"),
    R_KLUN ("Клюн"),
    R_KOROVIN ("Коровин"),
    R_KOSHELEV ("Кошелев"),
    R_KRACHKOVSKY ("Крачковский"),
    R_KRYJICKY ("Крыжицкий"),
    R_KUZNECOV ("Кузнецов"),
    R_KUINDJI ("Куинджи"),
    R_KUSTODIEV ("Кустодиев"),
    R_LAPCHENKO ("Лапченко"),
    R_LARIONOV ("Ларионов"),
    R_LEBEDEV ("Лебедев"),
    R_LEVITAN ("Левитан"),
    R_LEMOH ("Лемох"),
    R_LENTULOV ("Лентулов"),
    R_MAKOVSKY_VE ("Маковский В."),
    R_MAKOVSKY_KE ("Маковский К."),
    R_MAKSIMOV ("Максимов"),
    R_MALEVICH ("Малевич"),
    R_MALUTIN ("Малютин"),
    R_MALAVIN ("Малявин"),
    R_MASHKOV ("Машков"),
    R_MOSHIN ("Мошин"),
    R_MYLNIKOV ("Мыльников"),
    R_NESTEROV ("Нестеров"),
    R_PAKULIN ("Пакулин"),
    R_PASTERNAK ("Пастернак"),
    R_PEROV ("Перов"),
    R_PESTINSKY ("Пестинский"),
    R_PETROV_VODKIN ("Петров-Водкин"),
    R_PLASTOV ("Пластов"),
    R_POLENOV ("Поленов"),
    R_POPOV ("Попов (Московский)"),
    R_POPOVA ("Попова"),
    R_PUNI ("Пуни"),
    R_RAEV ("Раев"),
    R_REITERN ("Рейтерн"),
    R_REPIN ("Репин"),
    R_RERIH ("Рерих"),
    R_ROZANOVA ("Розанова"),
    R_RUSAKOVA ("Русакова"),
    R_RUTKOVSKY ("Рутковский"),
    R_RYLOV ("Рылов"),
    R_RYABUSHKIN ("Рябушкин"),
    R_RYANGINA ("Рянгина"),
    R_SAVRASOV ("Саврасов"),
    R_SAMOHVALOV ("Самохвалов"),
    R_SAPUNOV ("Сапунов"),
    R_SARYAN ("Сарьян"),
    R_SVETOSLAVSKY ("Светославский"),
    R_SEREBRAKOVA ("Серебрякова"),
    R_SEROV ("Серов"),
    R_SKOTTI ("Скотти"),
    R_SOMOV ("Сомов"),
    R_SURIKOV ("Суриков"),
    R_TATLIN ("Татлин"),
    R_TOROPOV ("Торопов"),
    R_TROPININ ("Тропинин"),
    R_UDALCOVA ("Удальцова"),
    R_FEDOTOV ("Федотов"),
    R_FEKLISTOV ("Феклистов"),
    R_FILONOV ("Филонов"),
    R_FLAVICKY ("Флавицкий"),
    R_FRENC ("Френц"),
    R_HARLAMOV ("Харламов"),
    R_CHERNECOV ("Чернецов"),
    R_CHERNYSHEV ("Чернышев"),
    R_SHAGAL ("Шагал"),
    R_SHEVCHENKO ("Шевченко"),
    R_SHISHKIN ("Шишкин"),
    R_SHTERNBERG ("Штернберг"),
    R_EKSTER ("Экстер"),
    R_UON ("Юон"),
    R_YAKOBI ("Якоби"),
    R_YAKOVLEV ("Яковлев"),
    R_YAROSHENKO ("Ярошенко");

    private final String artName;

    RusMusArtists(String artName) {
        this.artName = artName;
    }

    public String getArtName() {
        return artName;
    }


}
