package org.example.bot.settings.enums.artists;

public enum TretGalArtists {

    AIVAZOVSKY ("Айвазовский"),
    ANDREENKOV ("Андреенков"),
    ARCHIPOV ("Архипов"),
    BAKST ("Бакст"),
    BASYROV ("Басыров"),
    BELASHOV ("Белашов"),
    BESIN ("Безин"),
    BERINGOV ("Берингов"),
    BOGDANOV ("Богданов-Бельский"),
    BORISOV ("Борисов"),
    BORISOV_MUSATOV ("Борисов-Мусатов"),
    BOROVIKOVSKY ("Боровиковский"),
    BOCHAROV ("Бочаров"),
    BRAZ ("Браз"),
    BRODSKY ("Бродский"),
    BRULLOV ("Брюллов"),
    VASILEV ("Васильев"),
    VASNECOV_A ("Васнецов А."),
    VASNECOV_V ("Васнецов В."),
    VENECIANOV ("Венецианов"),
    VERECHAGIN ("Верещагин"),
    VOLKOV ("Волков"),
    VOLOSHIN ("Волошин"),
    VOROBEV ("Воробьев"),
    VRUBEL ("Врубель"),
    GE ("Ге"),
    GOLOVIN ("Головин"),
    GONCHAROVA ("Гончарова"),
    GORONOVICH ("Горонович"),
    DEMENTEV ("Дементьев"),
    JARENOVA ("Жаренова"),
    JILINKY ("Жилинский"),
    JUKOVSKY ("Жуковский"),
    ZAICEV ("Зайцев"),
    ZACHAROV ("Захаров"),
    ZVERKOV ("Зверьков"),
    IVANOV_AI ("Иванов А.И."),
    ISTOMIN ("Истомин"),
    KANDINSKY ("Кандинский"),
    KELIN ("Келин"),
    KIPRENSKY ("Кипренский"),
    KISELEV ("Киселев"),
    KOMAROV ("Комаров"),
    KONENKOV ("Коненков"),
    KORJEV ("Коржев"),
    KORIN ("Корин"),
    KOROVIN ("Коровин"),
    KRAVCHENKO ("Кравченко"),
    KRAMSKOY ("Крамской"),
    KUINDJI ("Куинджи"),
    KUPREYANOV ("Купреянов"),
    KUSTODIEV ("Кустодиев"),
    LAVROVA ("Лаврова"),
    LAGODA ("Лагода-Шишкина"),
    LAGORIO ("Лагорио"),
    LARIONOV ("Ларионов"),
    LEVITAN ("Левитан"),
    LENTULOV ("Лентулов"),
    LOSHAKOV ("Лоншаков"),
    LUBENNIKOV ("Лубенников"),
    MAVRINA ("Маврина"),
    MAKOVSKY_VE ("Маковский В."),
    MALEVICH ("Малевич"),
    MALAVIN ("Малявин"),
    MASHKOV ("Машков"),
    MILMAN ("Мильман"),
    NESTEROV ("Нестеров"),
    NESTEROVA ("Нестерова"),
    NIVINSKY ("Нивинский"),
    NIKICH ("Никич"),
    NIKONOV ("Никонов"),
    OSTROUCHOV ("Остроухов"),
    PAVLOVEC ("Павловец"),
    PEROV ("Перов"),
    PETROV_VODKIN ("Петров-Водкин"),
    PIROSNAMASHVILI ("Пиросманишвили"),
    POLENOV ("Поленов"),
    POPKOV ("Попков"),
    PUKIREV ("Пукирев"),
    RABIN ("Рабин"),
    REPIN ("Репин"),
    RERIH ("Рерих"),
    ROGINSKY ("Рогинский"),
    ROZANOVA ("Розанова"),
    ROKOTOV ("Рокотов"),
    RUBLEV ("Рублев"),
    SAVRASOV ("Саврасов"),
    SALACHOV ("Салахов"),
    SAPUNOV ("Сапунов"),
    SEROV ("Серов"),
    SITNIKOV ("Ситников"),
    SOMOV ("Сомов"),
    SOTNIKOV ("Сотников"),
    SUDEIKIN ("Судейкин"),
    SURIKOV ("Суриков"),
    TKACHEV ("Ткачев"),
    TOLSTOY ("Толстой"),
    TROPININ ("Тропинин"),
    TRUBECKOY ("Трубецкой"),
    TURNOVA ("Турнова"),
    TYRSA ("Тырса"),
    UDALCOVA ("Удальцова"),
    USHAKOV ("Ушаков"),
    FALK ("Фальк"),
    FEDOTOV ("Федотов"),
    FILONOV ("Филонов"),
    HOHRAKOV ("Хохряков"),
    CHASHNIC ("Чашник"),
    CHEKRYGIN ("Чекрыгин"),
    CHEREMUSHKIN ("Черемушкин"),
    SHANKS ("Шанкс"),
    SHACHOVSKY ("Шаховский"),
    SHEVCHENKO ("Шевченко"),
    SHISHKIN ("Шишкин"),
    CHEDRIN ("Щедрин"),
    CHIPICIN ("Щипицын"),
    ERASSI ("Эрасси"),
    YAROSHENKO ("Ярошенко");


    private final String artName;

    TretGalArtists(String artName) {
        this.artName = artName;
    }

    public String getArtName() {
        return artName;
    }


}
