package org.example.bot.settings.enums;

public enum TretGalArtists {

    ABUTKOV ("Абутков"),
    AIVAZOVSKY ("Айвазовский"),
    ALTMAN ("Альтман"),
    ANDREENKOV ("Андреенков"),
    ANNENKOV ("Анненков"),
    ARCHIPOV ("Архипов"),
    ARNAUTOV ("Арнаутов"),
    BAKST ("Бакст"),
    BASYROV ("Басыров"),
    BASHKIRCEVA("Башкирцева"),
    BELASHOV ("Белашов"),
    BELKIN ("Белкин"),
    BENUA ("Бенуа"),
    BESIN ("Безин"),
    BERINGOV ("Берингов"),
    BILIBIN ("Билибин"),
    BOGDANOV ("Богданов-Бельский"),
    BOGOLUBOV ("Боголюбов"),
    BONDAREVSKY ("Бондаревский"),
    BORISOV ("Борисов"),
    BORISOV_MUSATOV ("Борисов-Мусатов"),
    BOROVIKOVSKY ("Боровиковский"),
    BOCHAROV ("Бочаров"),
    BRAZ ("Браз"),
    BRODSKY ("Бродский"),
    BRONNIKOV ("Бронников"),
    BRULLOV ("Брюллов"),
    BRUNI ("Бруни"),
    VASILEV ("Васильев"),
    VASNECOV_A ("Васнецов А."),
    VASNECOV_V ("Васнецов В."),
    VENECIANOV ("Венецианов"),
    VENIG ("Вениг"),
    VERECHAGIN ("Верещагин"),
    VOLKOV ("Волков"),
    VOLOSHIN ("Волошин"),
    VOROBEV ("Воробьев"),
    VRUBEL ("Врубель"),
    GE ("Ге"),
    GINE ("Гине"),
    GOLOVIN ("Головин"),
    GONCHAROVA ("Гончарова"),
    GORONOVICH ("Горонович"),
    GRABAR ("Грабарь"),
    GRIGOREV ("Григорьев"),
    GUN ("Гун"),
    DELAVOSKADOVSKAYA ("Делла-Вос-Кардовская"),
    DEMENTEV ("Дементьев"),
    DEMIDOV ("Демидов"),
    DMITRIEV ("Дмитриев-Оренбургский"),
    DOBUJINSKY ("Добужинский"),
    DREVIN ("Древин"),
    DUBOVSKY ("Дубовский"),
    JARENOVA ("Жаренова"),
    JILINKY ("Жилинский"),
    JUKOVSKY ("Жуковский"),
    JURAVLEV ("Журавлев"),
    ZAICEV ("Зайцев"),
    ZACHAROV ("Захаров"),
    ZVERKOV ("Зверьков"),
    IVANOV_AA ("Иванов А.А."),
    IVANOV_AI ("Иванов А.И."),
    IVANOV_AM ("Иванов А.М."),
    IVANOV_SP ("Иванов С.П."),
    ISTOMIN ("Истомин"),
    KALMAKOV ("Калмаков"),
    KANDINSKY ("Кандинский"),
    KASATKIN ("Касаткин"),
    KELIN ("Келин"),
    KIVSHENKO ("Кившенко"),
    KIPRENSKY ("Кипренский"),
    KISELEV ("Киселев"),
    KLEVER ("Клевер"),
    KLODT ("Клодт фон Юргенсбург"),
    KLUN ("Клюн"),
    KOMAROV ("Комаров"),
    KONENKOV ("Коненков"),
    KORJEV ("Коржев"),
    KORIN ("Корин"),
    KOROVIN ("Коровин"),
    KOSHELEV ("Кошелев"),
    KRAVCHENKO ("Кравченко"),
    KRAMSKOY ("Крамской"),
    KRACHKOVSKY ("Крачковский"),
    KRYJICKY ("Крыжицкий"),
    KUZNECOV ("Кузнецов"),
    KUINDJI ("Куинджи"),
    KUPREYANOV ("Купреянов"),
    KUSTODIEV ("Кустодиев"),
    LAVROVA ("Лаврова"),
    LAGODA ("Лагода-Шишкина"),
    LAGORIO ("Лагорио"),
    LAPCHENKO ("Лапченко"),
    LARIONOV ("Ларионов"),
    LEBEDEV ("Лебедев"),
    LEVITAN ("Левитан"),
    LEMOH ("Лемох"),
    LENTULOV ("Лентулов"),
    LOSHAKOV ("Лоншаков"),
    LUBENNIKOV ("Лубенников"),
    MAVRINA ("Маврина"),
    MAKOVSKY_VE ("Маковский В."),
    MAKOVSKY_KE ("Маковский К."),
    MAKSIMOV ("Максимов"),
    MALEVICH ("Малевич"),
    MALUTIN ("Малютин"),
    MALAVIN ("Малявин"),
    MASHKOV ("Машков"),
    MILMAN ("Мильман"),
    MOSHIN ("Мошин"),
    MYLNIKOV ("Мыльников"),
    NESTEROV ("Нестеров"),
    NESTEROVA ("Нестерова"),
    NIVINSKY ("Нивинский"),
    NIKICH ("Никич"),
    NIKONOV ("Никонов"),
    OSTROUCHOV ("Остроухов"),
    PAVLOVEC ("Павловец"),
    PAKULIN ("Пакулин"),
    PASTERNAK ("Пастернак"),
    PEROV ("Перов"),
    PESTINSKY ("Пестинский"),
    PETROV_VODKIN ("Петров-Водкин"),
    PIROSNAMASHVILI ("Пиросманишвили"),
    PLASTOV ("Пластов"),
    POLENOV ("Поленов"),
    POPKOV ("Попков"),
    POPOV ("Попов"),
    PUKIREV ("Пукирев"),
    PUNI ("Пуни"),
    RABIN ("Рабин"),
    RAEV ("Раев"),
    REITERN ("Рейтерн"),
    REPIN ("Репин"),
    RERIH ("Рерих"),
    ROGINSKY ("Рогинский"),
    ROZANOV ("Розанов"),
    ROZANOVA ("Розанова"),
    ROKOTOV ("Рокотов"),
    RUBLEV ("Рублев"),
    RUSAKOVA ("Русакова"),
    RUTKOVSKY ("Рутковский"),
    RYLOV ("Рылов"),
    RYABUSHKIN ("Рябушкин"),
    RYANGINA ("Рянгина"),
    SAVRASOV ("Саврасов"),
    SALACHOV ("Салахов"),
    SAMOHVALOV ("Самохвалов"),
    SAPUNOV ("Сапунов"),
    SARYAN ("Сарьян"),
    SVETOSLAVSKY ("Светославский"),
    SEREBRAKOVA ("Серебрякова"),
    SEROV ("Серов"),
    SITNIKOV ("Ситников"),
    SKOTTI ("Скотти"),
    SOMOV ("Сомов"),
    SOTNIKOV ("Сотников"),
    SUDEIKIN ("Судейкин"),
    SURIKOV ("Суриков"),
    TATLIN ("Татлин"),
    TKACHEV ("Ткачев"),
    TOLSTOY ("Толстой"),
    TOROPOV ("Торопов"),
    TROPININ ("Тропинин"),
    TRUBECKOY ("Трубецкой"),
    TURNOVA ("Турнова"),
    TYRSA ("Тырса"),
    UDALCOVA ("Удальцова"),
    USHAKOV ("Ушаков"),
    FALK ("Фальк"),
    FEDOTOV ("Федотов"),
    FEKLISTOV ("Феклистов"),
    FILONOV ("Филонов"),
    FLAVICKY ("Флавицкий"),
    FRENC ("Френц"),
    HARLAMOV ("Харламов"),
    HOHRAKOV ("Хохряков"),
    CHASHNIC ("Чашник"),
    CHEKRYGIN ("Чекрыгин"),
    CHEREMUSHKIN ("Черемушкин"),
    CHERNECOV ("Чернецов"),
    CHERNYSHEV ("Чернышев"),
    SHAGAL ("Шагал"),
    SHANKS ("Шанкс"),
    SHACHOVSKY ("Шаховский"),
    SHEVCHENKO ("Шевченко"),
    SHISHKIN ("Шишкин"),
    SHTERNBERG ("Штернберг"),
    CHEDRIN ("Щедрин"),
    CHIPICIN ("Щипицын"),
    EKSTER ("Экстер"),
    ERASSI ("Эрасси"),
    UON ("Юон"),
    YAKOBI ("Якоби"),
    YAKOVLEV ("Яковлев"),
    YAROSHENKO ("Ярошенко");

    private final String artName;

    TretGalArtists(String artName) {
        this.artName = artName;
    }

    public String getArtName() {
        return artName;
    }


}
